### PR TITLE
Remove setfund #23

### LINKED ISSUE #23: Remove sponsoring of tspecs

### PR DESCRIPTION
**Pull request by soft-bagel-93**
Resolves #23

### CODE REVIEW

**Review by afalaleev — APPROVED** [review]

**Comment by afalaleev** [comment]
Looks good! Please rebase to fix conflicts.

**Comment by soft-bagel-93** [comment]
Hurrah, CI working.

**Comment by soft-bagel-93** [comment]
@afalaleev CI passed. Merge it, please.

**Comment by soft-bagel-93** [comment]
@s-medvedev you can merge

**Review by afalaleev — APPROVED** [review]

**Pull request merged**
